### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by eronx001** [burning-eggs/shooty#2]
Hey! I'm interested in helping with this, looks like a cool set up!
Is there anything you're looking to add that you might need help with?

**Comment by burning-eggs** [comment]
Heya @eronx001. I'm currently not working on this project (for now) because I've been crushed with finals.
I've already got the base of the game laid out. Only need to program it. After that, I'll start creating issues and accepting PRs.

**Comment by eronx001** [comment]
Cool! I forked it just for something to play with. Let me know if/when you want help.
